import pytest
from pexplore import pexplore
import click
from click.testing import CliRunner

def test_pexplore_cli():
    runner = CliRunner()
    with open('custom.json', 'w') as f:
        pdict = {"session_6888829a59ae4f4e83f4a8b89f65b4bc": {
    "aborted": false,
    "enabled_parser_names": [
      "syslog",
      "syslog/ssh",
      "syslog/cron",
      "olecf",
      "olecf/olecf_summary",
      "olecf/olecf_automatic_destinations",
      "olecf/olecf_document_summary",
      "olecf/olecf_default",
      "bencode",
      "bencode/bencode_utorrent",
      "bencode/bencode_transmission",
      "esedb",
      "esedb/msie_webcache",
      "esedb/file_history",
      "esedb/srum",
      "sqlite",
      "sqlite/windows_timeline",
      "sqlite/mackeeper_cache",
      "sqlite/imessage",
      "sqlite/chrome_extension_activity",
      "sqlite/android_calls",
      "sqlite/ls_quarantine",
      "sqlite/chrome_8_history",
      "sqlite/tango_android_tc",
      "sqlite/android_webviewcache",
      "sqlite/android_webview",
      "sqlite/zeitgeist",
      "sqlite/google_drive",
      "sqlite/chrome_autofill",
      "sqlite/twitter_ios",
      "sqlite/kodi",
      "sqlite/mac_document_versions",
      "sqlite/android_sms",
      "sqlite/twitter_android",
      "sqlite/kik_messenger",
      "sqlite/firefox_downloads",
      "sqlite/skype",
      "sqlite/hangouts_messages",
      "sqlite/chrome_27_history",
      "sqlite/appusage",
      "sqlite/firefox_cookies",
      "sqlite/firefox_history",
      "sqlite/mac_notificationcenter",
      "sqlite/safari_history",
      "sqlite/chrome_cookies",
      "sqlite/tango_android_profile",
      "dpkg",
      "chrome_preferences",
      "msiecf",
      "dockerjson",
      "gdrive_synclog",
      "firefox_cache",
      "filestat",
      "systemd_journal",
      "pls_recall",
      "java_idx",
      "zsh_extended_history",
      "chrome_cache",
      "xchatscrollback",
      "xchatlog",
      "utmp",
      "opera_typed_history",
      "binary_cookies",
      "czip",
      "czip/oxml",
      "plist",
      "plist/spotlight",
      "plist/plist_default",
      "plist/apple_id",
      "plist/time_machine",
      "plist/spotlight_volume",
      "plist/macuser",
      "plist/maxos_software_update",
      "plist/airport",
      "plist/macosx_install_history",
      "plist/macosx_bluetooth",
      "plist/safari_history",
      "plist/ipod_device",
      "selinux",
      "opera_global",
      "popularity_contest"
    ],
    "__type__": "AttributeContainer",
    "debug_mode": false,
    "preferred_encoding": "UTF-8",
    "product_name": "plaso",
    "__container_type__": "session",
    "command_line_arguments": "/usr/bin/log2timeline.py --parsers linux,syslog --logfile /data/plaso.log /data/tddd-cron.plaso /mnt/var/log",
    "analysis_reports_counter": {
      "__type__": "collections.Counter"
    },
    "completion_time": 1550423848698765,
    "parser_filter_expression": "linux,syslog",
    "event_labels_counter": {
      "__type__": "collections.Counter"
    },
    "start_time": 1550423844966901,
    "parsers_counter": {
      "utmp": 2,
      "__type__": "collections.Counter",
      "dpkg": 1376,
      "total": 1459,
      "filestat": 45,
      "syslog": 36
    },
    "product_version": "20190131",
    "identifier": "6888829a59ae4f4e83f4a8b89f65b4bc"
  },
  "session_80288dbec7ea47b59f4a6a39035e0d87": {
    "aborted": false,
    "enabled_parser_names": [
      "bencode",
      "bencode/bencode_utorrent",
      "bencode/bencode_transmission",
      "plist",
      "plist/macosx_install_history",
      "plist/macosx_bluetooth",
      "plist/maxos_software_update",
      "plist/spotlight_volume",
      "plist/ipod_device",
      "plist/macuser",
      "plist/time_machine",
      "plist/safari_history",
      "plist/plist_default",
      "plist/apple_id",
      "plist/spotlight",
      "plist/airport",
      "firefox_cache",
      "xchatscrollback",
      "zsh_extended_history",
      "opera_typed_history",
      "systemd_journal",
      "pls_recall",
      "chrome_cache",
      "dockerjson",
      "utmp",
      "syslog",
      "syslog/ssh",
      "syslog/cron",
      "filestat",
      "selinux",
      "xchatlog",
      "sqlite",
      "sqlite/chrome_autofill",
      "sqlite/chrome_27_history",
      "sqlite/google_drive",
      "sqlite/android_sms",
      "sqlite/android_webview",
      "sqlite/android_webviewcache",
      "sqlite/firefox_history",
      "sqlite/tango_android_profile",
      "sqlite/imessage",
      "sqlite/chrome_cookies",
      "sqlite/firefox_downloads",
      "sqlite/mackeeper_cache",
      "sqlite/android_calls",
      "sqlite/ls_quarantine",
      "sqlite/mac_notificationcenter",
      "sqlite/skype",
      "sqlite/tango_android_tc",
      "sqlite/chrome_8_history",
      "sqlite/chrome_extension_activity",
      "sqlite/mac_document_versions",
      "sqlite/twitter_ios",
      "sqlite/windows_timeline",
      "sqlite/safari_history",
      "sqlite/appusage",
      "sqlite/kodi",
      "sqlite/zeitgeist",
      "sqlite/hangouts_messages",
      "sqlite/kik_messenger",
      "sqlite/twitter_android",
      "sqlite/firefox_cookies",
      "gdrive_synclog",
      "binary_cookies",
      "java_idx",
      "chrome_preferences",
      "popularity_contest",
      "dpkg",
      "pe",
      "czip",
      "czip/oxml",
      "msiecf",
      "olecf",
      "olecf/olecf_default",
      "olecf/olecf_automatic_destinations",
      "olecf/olecf_document_summary",
      "olecf/olecf_summary",
      "esedb",
      "esedb/file_history",
      "esedb/srum",
      "esedb/msie_webcache",
      "opera_global"
    ],
    "__type__": "AttributeContainer",
    "debug_mode": false,
    "preferred_encoding": "UTF-8",
    "product_name": "plaso",
    "__container_type__": "session",
    "command_line_arguments": "/usr/bin/log2timeline.py --yara_rules /data/data/kiwi_passwords.yar --parsers linux,syslog,pe --logfile /data/plaso.log /data/tddd-cron.plaso /mnt/tmp",
    "analysis_reports_counter": {
      "__type__": "collections.Counter"
    },
    "completion_time": 1550423859749066,
    "parser_filter_expression": "linux,syslog,pe",
    "event_labels_counter": {
      "__type__": "collections.Counter"
    },
    "start_time": 1550423857713679,
    "parsers_counter": {
      "total": 58,
      "filestat": 51,
      "__type__": "collections.Counter",
      "pe": 7
    },
    "product_version": "20190131",
    "identifier": "80288dbec7ea47b59f4a6a39035e0d87"
  },
  "session_4be1956e1b074e3ebc042571d66f8444": {
    "aborted": false,
    "enabled_parser_names": [
      "chrome_cache",
      "popularity_contest",
      "opera_typed_history",
      "systemd_journal",
      "sqlite",
      "sqlite/firefox_cookies",
      "sqlite/google_drive",
      "sqlite/firefox_history",
      "sqlite/tango_android_profile",
      "sqlite/zeitgeist",
      "sqlite/hangouts_messages",
      "sqlite/twitter_ios",
      "sqlite/android_calls",
      "sqlite/kik_messenger",
      "sqlite/skype",
      "sqlite/windows_timeline",
      "sqlite/mac_notificationcenter",
      "sqlite/android_webview",
      "sqlite/chrome_27_history",
      "sqlite/chrome_cookies",
      "sqlite/android_webviewcache",
      "sqlite/mac_document_versions",
      "sqlite/firefox_downloads",
      "sqlite/twitter_android",
      "sqlite/chrome_autofill",
      "sqlite/mackeeper_cache",
      "sqlite/imessage",
      "sqlite/kodi",
      "sqlite/tango_android_tc",
      "sqlite/chrome_8_history",
      "sqlite/safari_history",
      "sqlite/appusage",
      "sqlite/ls_quarantine",
      "sqlite/android_sms",
      "sqlite/chrome_extension_activity",
      "chrome_preferences",
      "utmp",
      "dockerjson",
      "java_idx",
      "bencode",
      "bencode/bencode_transmission",
      "bencode/bencode_utorrent",
      "filestat",
      "xchatlog",
      "esedb",
      "esedb/file_history",
      "esedb/srum",
      "esedb/msie_webcache",
      "opera_global",
      "syslog",
      "syslog/ssh",
      "syslog/cron",
      "msiecf",
      "binary_cookies",
      "xchatscrollback",
      "firefox_cache",
      "plist",
      "plist/time_machine",
      "plist/airport",
      "plist/maxos_software_update",
      "plist/spotlight_volume",
      "plist/ipod_device",
      "plist/macosx_install_history",
      "plist/apple_id",
      "plist/spotlight",
      "plist/plist_default",
      "plist/safari_history",
      "plist/macuser",
      "plist/macosx_bluetooth",
      "gdrive_synclog",
      "pls_recall",
      "dpkg",
      "bash",
      "czip",
      "czip/oxml",
      "selinux",
      "olecf",
      "olecf/olecf_document_summary",
      "olecf/olecf_summary",
      "olecf/olecf_default",
      "olecf/olecf_automatic_destinations",
      "zsh_extended_history"
    ],
    "__type__": "AttributeContainer",
    "debug_mode": false,
    "preferred_encoding": "UTF-8",
    "product_name": "plaso",
    "__container_type__": "session",
    "command_line_arguments": "/usr/bin/log2timeline.py --parsers linux,syslog,bash --logfile /data/plaso.log /data/tddd-cron.plaso /mnt/home",
    "analysis_reports_counter": {
      "__type__": "collections.Counter"
    },
    "completion_time": 1550423871594744,
    "parser_filter_expression": "linux,syslog,bash",
    "event_labels_counter": {
      "__type__": "collections.Counter"
    },
    "start_time": 1550423869768202,
    "parsers_counter": {
      "total": 25,
      "bash": 7,
      "filestat": 18,
      "__type__": "collections.Counter"
    },
    "product_version": "20190131",
    "identifier": "4be1956e1b074e3ebc042571d66f8444"
  },
  "session_205f9dcc915c4529922f3df5e616b837": {
    "aborted": false,
    "__type__": "AttributeContainer",
    "debug_mode": false,
    "preferred_encoding": "UTF-8",
    "product_name": "plaso",
    "__container_type__": "session",
    "command_line_arguments": "/usr/bin/psort.py --analysis tagging --tagging-file /usr/local/share/plaso/tag_linux.txt -o json -w /data/tddd-cron-tagged.json /data/tddd-cron.plaso",
    "analysis_reports_counter": {
      "total": 1,
      "__type__": "collections.Counter",
      "tagging": 1
    },
    "completion_time": 1550423882337356,
    "event_labels_counter": {
      "T1156_bash_profile_and_bashrc": 3,
      "T1136_create_account": 1,
      "__type__": "collections.Counter",
      "T1215_Kernel_Modules_and_Extensions": 3,
      "ssh_logs": 4,
      "total": 47,
      "T1078_valid_accounts": 1,
      "T1003_credential_dumping": 24,
      "S0002_mimikatz": 24,
      "T1168_local_job_scheduling": 2,
      "T1098_account_manipulation": 8,
      "T1057_Process_Discovery": 1
    },
    "start_time": 1550423879505178,
    "parsers_counter": {
      "__type__": "collections.Counter"
    },
    "product_version": "20190131",
    "identifier": "205f9dcc915c4529922f3df5e616b837"
  }
}
        f.write(json.dumps(pdict))

    result = runner.invoke(cli, ['custom.json'])
    assert result.exit_code == 0



