version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no match is found
            - v1-dependecies-
    
      - run:
          name: setup python, venv, and install deps
          command: |
            pyenv install 3.6.3
            pyenv global 3.6.3
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
         paths:
           - ./venv
           key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run unit test
          command: |
            source venv/bin/activate
            py.test --cov=pexpore --cov-report html 
            tar czvf coverage-report.tgz htmlcov
      - store_artifacts:
          path: /home/circleci/repo/coverage-report.tgz
          destination: coverage-report.tgz
            
